#!/bin/bash


# ## Ejercicio: edad
# Crea un script llamado `edad` que reciba el año de nacimiento de una persona y calcule su edad, además le indicará cuántos años faltan para que cumpla 50. Evidentemente si la persona tiene 55 años le indicará los años que hace que cumplió 50.

# *Nota:* para saber el año actual se puede ejecutar `date +%Y`

if [ $# -ne  1 ];then
  echo "Debe indicar su año de nacimiento como primer parámetro" 1>&2
  exit 1
fi



annoActual=$( date +%Y )
annoNacimiento=$1



# ```sh
# $ ./edad
# Debe añadir su edad como parámetro.

# $ ./edad 2000
# Tienes 26 años.
# Cumplirás los 50 dentro de 24 años.

# $ ./edad 1970
# Tienes 56 años.
# Cumpliste los 50 hace 6 años.
# ```