#!/bin/bash


# Crea un fichero llamado systeminfo y añadelo a ~/.local/bin, acuérdate de asignarle permisos de ejecución para el usuario actual con chmod u+x systeminfo. Utiliza estos ficheros, órdenes y variables de entorno en el script para mostrar información del sistema al usuario.

# Nota: algunos de estos ficheros puede que no existan, ¿sabrías comprobarlo?

# Haz que la información se muestre bonita en pantalla. Una manera de lograrlo si la terminal soporta el uso del color es esta:

# echo -en "\033[1;36;7mSaludo:\033[0m ";
# echo "Hola caracola"

# Pruébalo y adáptalo a tus necesidades. Cambia el 36 por un 32, 31, 35...

# echo -en "\033[32mDespedida:\033[0m "
# echo "Hasta luego"

# Pruébalo y adáptalo a tus necesidades. Cambia el 32 por un 37, 31, 35...




if [ -f "/etc/os-release" ];then
  etiqueta="Nombre y versión de la distribución:"
  echo -e "\033[1;34;7m$etiqueta\033[0m ";
  
  grep "^PRETTY_NAME=" /etc/os-release | cut -d'"' -f2
else
  etiqueta="Nombre y versión de la distribución:"
  echo -e "\033[1;34;7m$etiqueta\033[0m ";
  grep "^DISTRIB_DESCRIPTION=" /etc/lsb-release | cut -d'"' -f2
fi

etiqueta="Versión del núcleo de Linux:"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
uname -r


echo




etiqueta="Corriente:"
echo -e "\033[1;34;7m$etiqueta\033[0m ";

conectado=$( cat /sys/class/power_supply/AC/online )
if [ $conectado -eq 1 ];then
  echo "Conectado a la red"
else
  echo "No conectado"
fi




etiqueta="Batería:"
echo -e "\033[1;34;7m$etiqueta\033[0m ";

conectado=$( cat /sys/class/power_supply/BAT0/status )
if [ "$conectado" == "charging" ];then
  echo "Cargando la batería"
elif [ "$conectado" == "Full" ];then
  echo "Batería cargada completamente"
else
  echo "Usando la batería"
fi



etiqueta="Capacidad de la batería:"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
bateria=$( cat /sys/class/power_supply/BAT0/capacity)
echo "$bateria%"

echo





etiqueta="Dispositivos Bluetooth conectados"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
bluetoothctl devices Connected

etiqueta="Dispositivos emparejados"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
bluetoothctl devices


echo



etiqueta="Direcciones IP"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
ip -brief a show

echo

etiqueta="Nombre del equipo y del usuario"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
echo "Nombre del equipo: $HOSTNAME"
echo "Usuario actual: $USER"

echo

etiqueta="Espacio en disco:"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
df -h | grep "^/dev/"

etiqueta="Memoria RAM (en megabytes):"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
free --mega


echo

# Temperatura: añadirle el símbolo
temp=$( cat /sys/class/hwmon/hwmon1/device/temp )
temp=$(( $temp / 1000 ))

etiqueta="Temperatura:"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
echo "$temp ºC"


etiqueta="CPU:"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
lscpu -e=CPU,MODELNAME,MHZ,MAXMHZ,MINMHZ

etiqueta="Carga de trabajo:"
echo -e "\033[1;34;7m$etiqueta\033[0m ";

# Carga de trabajo (1 minuto, 5 minutos, 15 minutos):
echo -n "(1 minuto)  : "
cat /proc/loadavg | cut -d" " -f1
echo -n "(5 minutos) : "
cat /proc/loadavg | cut -d" " -f2
echo -n "(15 minutos): "
cat /proc/loadavg | cut -d" " -f3



etiqueta="Tiempo de funcionamiento de la sesión:"
echo -e "\033[1;34;7m$etiqueta\033[0m ";
uptime -p

echo

etiqueta="Brillo de la pantalla (en un portátil):"
echo -e "\033[1;34;7m$etiqueta\033[0m ";

brillo_actual=$( cat /sys/class/backlight/intel_backlight/brightness )
brillo_max=$( cat /sys/class/backlight/intel_backlight/max_brightness )
porcentaje_brillo=$( echo "scale=2;$brillo_actual/$brillo_max*100" | bc -l )

echo "Brillo actual: $brillo_actual"
echo "Brillo máximo: $brillo_max"
echo "% brillo: $porcentaje_brillo %"



